# Generated by Django 4.2.5 on 2023-09-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travels',
            name='start_date',
            field=models.DateField(),
        ),
    ]
